FROM caddy:2.11.4-builder-alpine AS builder
RUN xcaddy build --with github.com/caddy-dns/duckdns

FROM caddy:2.11.4-alpine
RUN apk add --no-cache nss-tools
COPY --from=builder /usr/bin/caddy /usr/bin/caddy
